### PR TITLE
Fixes for compatibility with AAPT2.

### PR DESCRIPTION
**Pull request by rogerjames99**
This allows this project to be built with Android Studio v3+.

### CODE REVIEW

**Comment by BrenuDev** [comment]
Hi,
This code is not used anymore.
We switched over to the Xamarin platform.

**Comment by rogerjames99** [comment]
Hi Brett,

I realise that. I was just posting it for anyone else who might want to try 
building it. As an aside as you appear to have withdrawn the product do you 
hold any old stock? If so how many units and how much would you want for it?

Roger

**Comment by rogerjames99** [comment]
Brecht,

My apologies for mispelling your name in the last message.

Roger

**Comment by BrenuDev** [comment]
Hi 

No worries about the name :)
Please contact our Product Manager regarding the product, you can contact him at 
psi (at) velleman (dot) eu. He's already informed about it.

Best Regards,
Brecht

**Pull request closed without merging**
